name: Github Actions Zappy
on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

jobs:
  check_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: make re
      timeout-minutes: 1
  push_to_mirror:
    needs:
      - check_compilation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: ${{ secrets.REPOSITORY_SSH }}
        ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
